version: "3.9"
name: "sbt-demo-320"
services:
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
  mysql:
    container_name: mysql
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3306:3306"
    volumes:
      -
  redis:
    container_name: redis
    image: redis:7.2.3-alpine
    ports:
      - "6379:6379"
    volumes:
      -
